### PR TITLE
(Impr) Dockerfile now is the docker way

### PR DESCRIPTION
**Pull request by linuxbandit**
The source files are copied on build time and not mounted.
This is the way the Dockerfiles should be written. Unfortunately
due to scopes, the Dockerfile cannot be inside docker, because
the COPY operation does not go above (..) the Dockerfile position.
Alternative to this could be to 'RUN git clone [....]' but this
approach is too rigid: in the way proposed, the files can still
be modified and the image rebuilt.

Supersedes #1 which had a conflict

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
one big question for all of this PRs: won't it break anything if I will deploy it and re-start the whole system (since it's the manifest change)?

**Comment by linuxbandit** [comment]
the best course of actions is to upgrade one at a time

e.g. IN PAIR (4 eyes are better than 2) one night we pull the repo oms-docker at the latest master
then we rebuild events
then we rebuild statutory
then we rebuild frontend
then we rebuild core

I think that (in the order) would be good for preventing stuff. Also anyway, time to use staging appropriately ;p

**Comment by serge1peshcoff** [comment]
@grasshopper is this up-to-date? and also PRs on the same on events and other repos

**Comment by linuxbandit** [comment]
I will close it but I want to do one thing first

**Pull request closed without merging**
