### PR TITLE
impr: docker files are the docker way

### PR DESCRIPTION
**Pull request by linuxbandit**
supersedes #2 

Similar to:
https://github.com/AEGEE/oms-discounts/pull/2
https://github.com/AEGEE/oms-events/pull/58

### CODE REVIEW

**Comment by linuxbandit** [comment]
I think the conflict comes from the merge you just did

**Comment by linuxbandit** [comment]
no, would be complaining about the docker-compose, not the dockerfile... hm

**Comment by serge1peshcoff** [comment]
I'll resolve it, don't worry

**Comment by serge1peshcoff** [comment]
Superseded by https://github.com/AEGEE/oms-statutory/pull/101

**Pull request closed without merging**
